rois_ST<-c("mprage_jlf_vol_L_Accumbens_Area","mprage_jlf_vol_L_Caudate","mprage_jlf_vol_L_Pallidum","mprage_jlf_vol_L_Putamen","mprage_jlf_vol_L_Thalamus_Proper","mprage_jlf_vol_R_Accumbens_Area","mprage_jlf_vol_R_Caudate","mprage_jlf_vol_R_Pallidum","mprage_jlf_vol_R_Putamen","mprage_jlf_vol_R_Thalamus_Proper")
rois_L_Lim<-c("mprage_jlf_vol_L_Amygdala","mprage_jlf_vol_L_Hippocampus","mprage_jlf_vol_L_PHG","mprage_jlf_vol_L_ACgG","mprage_jlf_vol_L_GRe","mprage_jlf_vol_L_MCgG","mprage_jlf_vol_L_PCgG","mprage_jlf_vol_R_Amygdala","mprage_jlf_vol_R_Hippocampus","mprage_jlf_vol_R_PHG","mprage_jlf_vol_R_ACgG","mprage_jlf_vol_R_GRe","mprage_jlf_vol_R_MCgG","mprage_jlf_vol_R_PCgG")
rois_L_FrOrb<-c("mprage_jlf_vol_L_AOrG","mprage_jlf_vol_L_POrG","mprage_jlf_vol_L_FO","mprage_jlf_vol_L_FRP","mprage_jlf_vol_L_LOrG","mprage_jlf_vol_L_MOrG",
"mprage_jlf_vol_L_OpIFG","mprage_jlf_vol_R_AOrG","mprage_jlf_vol_R_POrG","mprage_jlf_vol_R_FO","mprage_jlf_vol_R_FRP","mprage_jlf_vol_R_LOrG",
"mprage_jlf_vol_R_MOrG","mprage_jlf_vol_R_OpIFG")
rois_L_FrDors<-c("mprage_jlf_vol_L_MSFG","","","mprage_jlf_vol_L_PrG","mprage_jlf_vol_L_MFC","mprage_jlf_vol_L_MFG","mprage_jlf_vol_L_SFG","mprage_jlf_vol_L_SMC",
"mprage_jlf_vol_L_OrIFG","mprage_jlf_vol_L_MPrG","mprage_jlf_vol_L_TrIFG","mprage_jlf_vol_R_MSFG","","mprage_jlf_vol_R_PrG","mprage_jlf_vol_R_MFC","mprage_jlf_vol_R_MFG","mprage_jlf_vol_R_SFG","mprage_jlf_vol_R_SMC","mprage_jlf_vol_R_OrIFG","mprage_jlf_vol_R_MPrG","mprage_jlf_vol_R_TrIFG")
rois_L_Tem<-c("mprage_jlf_vol_L_ITG","mprage_jlf_vol_L_MTG","mprage_jlf_vol_L_PP","mprage_jlf_vol_L_PT","mprage_jlf_vol_L_AIns","mprage_jlf_vol_L_PIns",
"mprage_jlf_vol_L_SCA","mprage_jlf_vol_L_STG","mprage_jlf_vol_L_TMP","mprage_jlf_vol_L_TTG","mprage_jlf_vol_L_Ent","mprage_jlf_vol_L_FuG","mprage_jlf_vol_R_ITG","mprage_jlf_vol_R_MTG","mprage_jlf_vol_R_PP","mprage_jlf_vol_R_PT","mprage_jlf_vol_R_AIns","mprage_jlf_vol_R_PIns","mprage_jlf_vol_R_SCA","mprage_jlf_vol_R_STG","mprage_jlf_vol_R_TMP","mprage_jlf_vol_R_TTG","mprage_jlf_vol_R_Ent","mprage_jlf_vol_R_FuG")
rois_L_Occ<-c("mprage_jlf_vol_L_Calc","mprage_jlf_vol_L_IOG","mprage_jlf_vol_L_Cun","mprage_jlf_vol_L_LiG","mprage_jlf_vol_L_MOG","mprage_jlf_vol_L_OCP","mprage_jlf_vol_L_OFuG","mprage_jlf_vol_L_SOG","mprage_jlf_vol_R_Calc","mprage_jlf_vol_R_IOG","mprage_jlf_vol_R_Cun","mprage_jlf_vol_R_LiG","mprage_jlf_vol_R_MOG","mprage_jlf_vol_R_OCP","mprage_jlf_vol_R_OFuG","mprage_jlf_vol_R_SOG")
rois_L_Par<-c("mprage_jlf_vol_L_AnG","mprage_jlf_vol_L_GEe","mprage_jlf_vol_L_MPoG","mprage_jlf_vol_L_PCu","mprage_jlf_vol_L_PO","mprage_jlf_vol_L_PoG",
"mprage_jlf_vol_L_SMG","mprage_jlf_vol_L_SPL","mprage_jlf_vol_L_CO","mprage_jlf_vol_R_AnG","mprage_jlf_vol_R_GRe","mprage_jlf_vol_R_MPoG","mprage_jlf_vol_R_PCu","mprage_jlf_vol_R_PO","mprage_jlf_vol_R_PoG","mprage_jlf_vol_R_SMG","mprage_jlf_vol_R_SPL","mprage_jlf_vol_R_CO")

