tmp1 <- read.csv('./femaleFitBetas.csv')
tmp2 <- read.csv("./femaleRFImportance.csv")
thing1 <- merge(tmp1, tmp2, by = "V3")
attach(thing1)
val1 <- cor(output.Vol.x, output.Vol.y, method = "s", use = "complete")
val2 <- cor(output.CBF.x, output.CBF.y, method = "s", use = "complete")
val3 <- cor(output.GMD.x, output.GMD.y, method = "s", use = "complete")
val4 <- cor(output.CT.x, output.CT.y, method = "s", use = "complete")
val5 <- cor(output.REHO.x, output.REHO.y, method = "s", use = "complete")
val6 <- cor(output.ALFF.x, output.ALFF.y, method = "s", use = "complete")
val7 <- cor(output.TR.x, output.TR.y, method = "s", use = "complete")
val8 <- cor(output.RD.x, output.RD.y, method = "s", use = "complete")
val9 <- cor(output.AD.x, output.AD.y, method = "s", use = "complete")
detach(thing1)
outputFemale <- c(val1, val2, val3, val4, val5, val6, val7, val8, val9)

tmp1 <- read.csv('./maleFitBetas.csv')
tmp2 <- read.csv("./maleRFImportance.csv")
thing1 <- merge(tmp1, tmp2, by = "V3")
attach(thing1)
val1 <- cor(output.Vol.x, output.Vol.y, method = "s", use = "complete")
val2 <- cor(output.CBF.x, output.CBF.y, method = "s", use = "complete")
val3 <- cor(output.GMD.x, output.GMD.y, method = "s", use = "complete")
val4 <- cor(output.CT.x, output.CT.y, method = "s", use = "complete")
val5 <- cor(output.REHO.x, output.REHO.y, method = "s", use = "complete")
val6 <- cor(output.ALFF.x, output.ALFF.y, method = "s", use = "complete")
val7 <- cor(output.TR.x, output.TR.y, method = "s", use = "complete")
val8 <- cor(output.RD.x, output.RD.y, method = "s", use = "complete")
val9 <- cor(output.AD.x, output.AD.y, method = "s", use = "complete")
detach(thing1)
outputMale <- c(val1, val2, val3, val4, val5, val6, val7, val8, val9)

output <- cbind(c('Vol', 'CBF', 'GMD', 'CT', 'Reho', 'Alff', 'TR', 'RD', 'AD'), outputFemale, outputMale)
write.csv(output, 'rfImpBetaCorVals.csv', quote=F, row.names=F)
